name: Jetty Server

on:
  push:
    branches:
      - main

jobs:
  jetty:
    runs-on: self-hosted
    steps:
      - name: Set up Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '3.0.9'  # Specify the desired Groovy version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Jetty
        run: |
          groovy -e '
            import org.mortbay.jetty.Server
            import org.mortbay.jetty.servlet.*
            import groovy.servlet.*

            def startJetty() {
                def jetty = new Server(9090)
                def context = new Context(jetty, "/", Context.SESSIONS)
                context.setWelcomeFiles(["webserverIndex.groovy"] as String[])
                context.resourceBase = "."
                context.addServlet(GroovyServlet, "*.groovy")
                jetty.start()
            }

            println "Starting Jetty on port 9090, press Ctrl+C to stop."
            startJetty()
          '
